<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Password_showPass</name>
   <tag></tag>
   <elementGuidId>f3881304-1381-40bd-acd5-4361bfb10dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showPass</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='showPass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a046ee55-67c0-45eb-ac07-63a4176192fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dd8e3cb3-c64b-4daf-b9e2-c8459b5695a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showPass</value>
      <webElementGuid>6683f6f0-c238-4143-b05c-0c12b2568df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showPass&quot;)</value>
      <webElementGuid>e8ab37ac-d996-4058-978a-036cee922ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='showPass']</value>
      <webElementGuid>19c03355-ab65-40ea-9025-f1adb99e70f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>5fd0638c-62e3-47a1-bc11-90f32d7dc5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'showPass']</value>
      <webElementGuid>21b9901b-3f42-4236-b487-4d0ada8ab143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
