<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Region</name>
   <tag></tag>
   <elementGuidId>f72ad118-a35b-4ae7-b88c-08caa7474db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-region-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-region-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>94f0286b-c2a5-4582-878e-6092e4189fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2a2580aa-e9c4-4554-8921-a4d2f3a40917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-region-container</value>
      <webElementGuid>ee12186b-fd0f-4a4c-bbf2-7d5e9df269d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d365e6b8-78a8-4581-b4ed-f2ddf3d567ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff7d60de-d87d-4f58-81af-be50fb10121d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Region</value>
      <webElementGuid>71452363-6df1-4d64-a4b7-1906d58df273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Region</value>
      <webElementGuid>db6fc541-4b36-4522-8281-bc7638f42025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-region-container&quot;)</value>
      <webElementGuid>18f5c985-75c8-448e-a91c-efefe47af204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-region-container']</value>
      <webElementGuid>d0da6eed-f580-4048-b938-d7b52fa0f15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[1]/following::span[5]</value>
      <webElementGuid>95fa3ec9-f728-4071-b4ac-afe3dd9bbe3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company / Plant'])[1]/preceding::span[3]</value>
      <webElementGuid>6955848b-1c13-491e-bea0-040a7c92cbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transportir / Distributor'])[2]/preceding::span[4]</value>
      <webElementGuid>e26d1db7-b22a-4c5a-b80f-c9a4a4d64e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>5f728c4e-94a8-40ee-9375-07fb9daf1bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-region-container' and @title = 'Pilih Region' and (text() = 'Pilih Region' or . = 'Pilih Region')]</value>
      <webElementGuid>3a77bd5d-2fc5-49e7-9754-c71e86a6af38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
