<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Password_showPass</name>
   <tag></tag>
   <elementGuidId>342ec03d-b109-447a-8831-44023ef9cdcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showPass</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='showPass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19515c60-c697-4604-8da3-60fa1edb226f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8f6605b2-194a-4d36-8554-36806c0371d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showPass</value>
      <webElementGuid>d6184e0d-95eb-445e-a5e5-c4ab0ce3f770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showPass&quot;)</value>
      <webElementGuid>d96c5934-5ab4-4d61-bb7f-2f537aaea93f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='showPass']</value>
      <webElementGuid>3e89a6fc-780f-4f41-9561-c02a68f36fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a099588c-fa81-446e-9c86-84adcf555fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'showPass']</value>
      <webElementGuid>ac7e3459-c1c0-4c54-bd23-1acb52d59712</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
