<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pupuk Kujang</name>
   <tag></tag>
   <elementGuidId>02503711-c920-4dd7-b789-aa3497cbc799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-company-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-company-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8162844d-a2a2-4731-9e1a-1fc1a2c3cf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>67193d02-f1d2-42d5-a19e-a8ba7c068a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-company-container</value>
      <webElementGuid>56d45c49-01a9-4678-a8f8-1a6b3098a337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>35f28a85-e58b-42d8-aad6-ebd18ba396ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff8f2b10-82fe-4893-82de-3809e787fa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pupuk Kujang</value>
      <webElementGuid>092dbee7-60fb-4cbc-9948-51b4d81921a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pupuk Kujang</value>
      <webElementGuid>38b44e25-e988-4664-891d-613655415cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-company-container&quot;)</value>
      <webElementGuid>365c819d-34eb-4fff-b686-46aa2999baec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-company-container']</value>
      <webElementGuid>cfb3aa96-94ef-4c44-85a8-13bbeaad0d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company / Plant'])[1]/following::span[5]</value>
      <webElementGuid>6fc7c993-3baf-42fe-8126-dd7bbf8898f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JABAR JATENG'])[2]/following::span[7]</value>
      <webElementGuid>302df2ea-f4a7-46f7-9dfc-1f34b2488739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::span[3]</value>
      <webElementGuid>1bcef3ab-3c3c-47e6-949b-d178cf713347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/preceding::span[3]</value>
      <webElementGuid>c8b08328-f03d-4a8f-aa10-88b02d5fa94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/span/span/span/span</value>
      <webElementGuid>4e4a6e28-4998-4362-8f97-df8448c6d8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-company-container' and @title = 'Pupuk Kujang' and (text() = 'Pupuk Kujang' or . = 'Pupuk Kujang')]</value>
      <webElementGuid>b55f7f4b-c235-47b3-93e4-c72f724995e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
